// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package category_test

import (
	domain "aszaychik/smartcafe-api/domain"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *CategoryRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *CategoryRepository) FindAll() ([]domain.Category, error) {
	ret := _m.Called()

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCategoryId provides a mock function with given fields: categoryId
func (_m *CategoryRepository) FindByCategoryId(categoryId int) ([]domain.Category, error) {
	ret := _m.Called(categoryId)

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Category, error)); ok {
		return rf(categoryId)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Category); ok {
		r0 = rf(categoryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(categoryId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *CategoryRepository) FindById(id int) (*domain.Category, error) {
	ret := _m.Called(id)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: categoryName
func (_m *CategoryRepository) FindByName(categoryName string) (*domain.Category, error) {
	ret := _m.Called(categoryName)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Category, error)); ok {
		return rf(categoryName)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Category); ok {
		r0 = rf(categoryName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(categoryName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: category
func (_m *CategoryRepository) Save(category *domain.Category) (*domain.Category, error) {
	ret := _m.Called(category)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Category) (*domain.Category, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(*domain.Category) *domain.Category); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Category) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: category, id
func (_m *CategoryRepository) Update(category *domain.Category, id int) (*domain.Category, error) {
	ret := _m.Called(category, id)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Category, int) (*domain.Category, error)); ok {
		return rf(category, id)
	}
	if rf, ok := ret.Get(0).(func(*domain.Category, int) *domain.Category); ok {
		r0 = rf(category, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Category, int) error); ok {
		r1 = rf(category, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
