name: Docker Image CI

on:
  push:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smartcafe:latest

      - name: Connect SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ secrets.CONTAINER_NAME }} || true
            docker rm ${{ secrets.CONTAINER_NAME }} || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/smartcafe || true
            docker run --name ${{ secrets.CONTAINER_NAME }} -p 8080:8080 -d \
              -v $(pwd)/uploads:/app/uploads \
              -e DB_HOST=${{secrets.DB_HOST}} \
              -e DB_PORT=${{secrets.DB_PORT}} \
              -e DB_NAME=${{secrets.DB_NAME}} \
              -e DB_USERNAME=${{secrets.DB_USERNAME}} \
              -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
              -e JWT_SECRET=${{secrets.JWT_SECRET}} \
              -e X_API_KEY=${{secrets.X_API_KEY}} \
              -e MIDTRANS_SERVER_KEY=${{secrets.MIDTRANS_SERVER_KEY}} \
              -e WIFI_SECRET_KEY=${{secrets.WIFI_SECRET_KEY}} \
              -e AWS_REGION=${{secrets.AWS_REGION}} \
              -e AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} \
              -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
              -e AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}} \
              ${{ secrets.DOCKERHUB_USERNAME }}/smartcafe
